- name: Check if initial admin password file exists
  stat:
    path: "{{ nexus_data_dir }}/admin.password"
  register: admin_pwd_file
  run_once: true

- name: Read initial admin password
  slurp:
    path: "{{ nexus_data_dir }}/admin.password"
  register: admin_pwd_raw
  when: admin_pwd_file.stat.exists
  run_once: true
  no_log: true

- name: Set initial admin password
  set_fact:
    nexus_initial_admin_password: "{{ admin_pwd_raw.content | b64decode | trim }}"
  when: admin_pwd_file.stat.exists
  run_once: true
  no_log: true

- name: Change admin password (first-time only)
  uri:
    url: "{{ nexus_healthcheck_scheme }}://{{ nexus_healthcheck_host }}:{{ nexus_healthcheck_port }}/service/rest/v1/security/users/admin/change-password"
    method: PUT
    user: admin
    password: "{{ nexus_initial_admin_password }}"
    force_basic_auth: true
    validate_certs: false
    body: "{{ nexus_admin_password }}"
    body_format: raw
    status_code: 204
  when: admin_pwd_file.stat.exists
  run_once: true
  no_log: true