all:
  vars:
    ansible_user: root
    ansible_password: rootpass
    ansible_connection: ssh
    ansible_become: true
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
  children:
    nexus:
      hosts:
        nexus01:
          ansible_host: nexus01
        nexus02:
          ansible_host: nexus02
        nexus03:
          ansible_host: nexus03
