---
- name: Validate repository list
  ansible.builtin.assert:
    that:
      - nexus_repositories is defined
      - nexus_repositories is iterable
    fail_msg: "nexus_repositories must be a list."
  run_once: true

- name: Manage Nexus repositories
  ansible.builtin.include_tasks: manage_one_repository.yml
  loop: "{{ nexus_repositories }}"
  loop_control:
    loop_var: nexus_repo
    label: "{{ nexus_repo.name }}"
  run_once: true


  